version: '2'
services:
  orderbackend-app:
    image: orderbackend
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://orderbackend-postgresql:5432/orderBackend
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  orderbackend-postgresql:
    extends:
      file: postgresql.yml
      service: orderbackend-postgresql
